#!/usr/bin/env python3
"""Find the server names used by the apps in apps/*.json.

Each apps/<name>.json maps an app to its official root domains (researched from the
apps' store listings). For every domain this asks the public Certificate Transparency
logs (crt.sh, Cert Spotter as backup) for all server names issued under it and writes
data/<name>.txt, which build.py uses as a source for <name>.txt.

Only names under the listed root domains are kept, so shared services (CDNs,
Google, Facebook...) are never added. If crt.sh fails for a domain, the names found
for it last time are kept. Usage: python3 scripts/discover_apps.py [apps/<name>.json ...]   (default: all)
"""
import concurrent.futures
import datetime
import json
import os
import random
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAME_RE = re.compile(r"^(?=.{1,253}$)(?!-)[a-z0-9_-]{1,63}(?:\.(?!-)[a-z0-9_-]{1,63})+$")
# Optional local cache of crt.sh JSON responses (<dir>/<domain>.json), handy for testing.
CACHE = os.environ.get("CRT_CACHE")
# Stop starting new lookups after this many minutes (crt.sh can be very slow); domains not
# reached keep last run's names. Order is shuffled so all domains get refreshed over time.
DEADLINE = time.time() + 60 * float(os.environ.get("DISCOVERY_MINUTES", "35"))


def get_json(url, tries):
    req = urllib.request.Request(url, headers={"User-Agent": "Pi-Hole-Block-Lists discovery"})
    last = None
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                return json.loads(resp.read())
        except Exception as e:  # noqa: BLE001 - CT services are often busy; retry
            last = e
            time.sleep(10 * (attempt + 1))
    raise last


def keep(domain, raw_names):
    names = set()
    for name in raw_names:
        name = name.strip().lower().lstrip("*.").rstrip(".")
        if (name == domain or name.endswith("." + domain)) and NAME_RE.match(name):
            names.add(name)
    return names


def certspotter_names(domain):
    """Backup source: Cert Spotter (newer certificates only, paginated)."""
    names, after = set(), None
    for _ in range(10):
        url = ("https://api.certspotter.com/v1/issuances?domain=%s&include_subdomains=true&expand=dns_names"
               % urllib.parse.quote(domain)) + ("&after=%s" % after if after else "")
        page = get_json(url, 2)
        if not page:
            break
        names |= keep(domain, (n for cert in page for n in cert.get("dns_names", [])))
        after = page[-1]["id"]
    return names


def crt_names(domain):
    if time.time() > DEADLINE and not (CACHE and Path(CACHE, domain + ".json").exists()):
        raise TimeoutError("time budget used up")
    if CACHE and Path(CACHE, domain + ".json").exists():
        certs = json.loads(Path(CACHE, domain + ".json").read_bytes())
    else:
        try:
            certs = get_json("https://crt.sh/?q=%s&output=json" % urllib.parse.quote("%." + domain), 4)
        except Exception:  # noqa: BLE001
            return certspotter_names(domain)
    return keep(domain, (n for cert in certs for n in cert.get("name_value", "").split("\n")))


def previous_names(out):
    if not out.exists():
        return set()
    return {l.strip() for l in out.read_text(encoding="utf-8").splitlines() if l.strip() and not l.startswith("#")}


def discover(apps_file):
    out = ROOT / "data" / (apps_file.stem + ".txt")
    print("== %s" % apps_file.name)
    apps = json.loads(apps_file.read_text(encoding="utf-8"))
    roots = sorted({d for app in apps.values() for d in app["domains"]})
    random.shuffle(roots)
    old = previous_names(out)
    found, failed = {}, []
    with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
        futures = {pool.submit(crt_names, d): d for d in roots}
        for fut in concurrent.futures.as_completed(futures):
            d = futures[fut]
            try:
                found[d] = fut.result()
                print("  ok   %-24s %6d names" % (d, len(found[d])))
            except Exception as e:  # noqa: BLE001
                failed.append(d)
                found[d] = {n for n in old if n == d or n.endswith("." + d)}
                print("  FAIL %-24s %s (kept %d previous names)" % (d, e, len(found[d])))

    lines = [
        "# App servers discovered from Certificate Transparency logs.",
        "# Generated by scripts/discover_apps.py from apps/%s. Do not edit by hand." % apps_file.name,
        "# Last discovery: %s" % datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d"),
    ]
    for app, meta in apps.items():
        lines.append("")
        lines.append("# %s" % app)
        names = set(meta["domains"])
        for d in meta["domains"]:
            names |= found.get(d, set())
        lines.extend(sorted(names))
    out.parent.mkdir(exist_ok=True)
    new = "\n".join(lines) + "\n"
    strip = lambda t: [l for l in t.splitlines() if not l.startswith("# Last discovery")]
    if not out.exists() or strip(out.read_text(encoding="utf-8")) != strip(new):
        out.write_text(new, encoding="utf-8")
    print("%d apps, %d root domains, %d failed" % (len(apps), len(roots), len(failed)))
    return len(failed) > len(roots) / 2


def main():
    files = [Path(f) for f in sys.argv[1:]] or sorted((ROOT / "apps").glob("*.json"))
    bad = [f.name for f in files if discover(f.resolve())]
    if bad:
        sys.exit("lookups failed for most domains in %s; previous names were kept" % ", ".join(bad))


if __name__ == "__main__":
    main()
